apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
  labels:
    name: ingress-service
spec:
  rules:
  - host: ticketing.dev
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/api/users/(.*)"
        backend:
          service:
            name: auth-svc
            port:
              number: 8000
      - pathType: ImplementationSpecific
        path: "/api/tickets/(.*)"
        backend:
          service:
            name: ticket-svc
            port:
              number: 8001
