apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-deployment
spec:
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      labels:
        app: ticket
    spec:
      containers:
      - name: ticket-deployment
        image: navaneethvinod/ticket-service
        env: 
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: ticket-mongo-uri-secret
                key: MONGO_URI
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: express-session-secret
                key: SESSION_SECRET
        resources:  
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-svc
spec:
  selector:
    app: ticket
  ports:
  - port: 8001
    targetPort: 8001
